### ISSUE TITLE
Add back ping method

### ISSUE THREAD

**Issue by andig** [influxdata/influxdb-client-go#105]
Please add back ping or similar method to verify that:
- endpoint actually exists
- endpoint credentials are valid

Otherwise applications would only identify very late- when actually writing data- that configuration is flawed. This is especially needed when applications only ever write asynchronously.

**Comment by vlastahajek** [comment]
@andig, Ping was replaced by [Ready](https://github.com/influxdata/influxdb-client-go/blob/master/client.go#L51). This serves for checking the availability of the InfuxDB 2 server. 

In the previous versions, it was called Ping due to legacy reasons.
 
A similar method, Health, will be added in the next release.

However, those server endpoints are not authenticated, so it is not possible to check credentials using them.
