### ISSUE TITLE
how can i set precision when influx.Write()?

### ISSUE THREAD

**Issue by mouyong** [influxdata/influxdb-client-go#23]

**Comment by docmerlin** [comment]
Thanks for brining this up, but I don't think it needs to be set.be set for the client.  The `precision` field is the time units that the time is in, not some sort of unit truncation (because some clients may have time as a unix seconds epoc or ms epic or something else.    Because the client accept a time.Time, we can just always use nanosecond units for the transmission.  If you want to store at a lower precision the way to do it would be to `Round` or `Truncate` the `time.Times` in the Metric.

**Comment by docmerlin** [comment]
If what I said is understandable, I can go ahead and close the issue.  If not, I can explain further.

**Comment by mouyong** [comment]
What does Round or Truncate mean? What should I do with time. Time? I don't quite understand. It means I don't need to set the accuracy. Is it okay to use time. Time directly?

**Comment by docmerlin** [comment]
> What does Round or Truncate mean?

If you want to reduce the precision of the measurement... if you want it to show seconds instead of nanoseconds, just use `Time.Round` or `time.Truncate` on whatever time.Time you use, directly.
You don't have to do this though, you don't need to set precision.

> I don't quite understand. It means I don't need to set the accuracy. Is it okay to use time. Time directly? 
yes.

-i'm going to go ahead and close this issue.  Feel free to ask any more questions if you have them.
